import { Navbar } from '@org/ui-components';
import { Container } from '@mui/material';
import type { Metadata } from 'next';
import ThemeRegistry from '@/theme/ThemeRegistry';
import QueryProvider from '@/providers/QueryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <ThemeRegistry>
            <Navbar />

            <Container maxWidth="lg" sx={{ py: 4 }}>
              {children}
            </Container>
          </ThemeRegistry>
        </QueryProvider>
      </body>
    </html>
  );
}
